daysUntilClose: 7
responseRequiredLabel: "more information needed"
closeComment: >
  This issue has been automatically closed because there has been no response
  to the request for more information from the original author. With only the
  information that is currently available, we can't take an action. Please,
  reach out if you have the needed answers, so that we can investigate further.
